words = [
    "asus",
    "bcdboot",
    "btrfs",
    "catppuccin",
    "chezmoi",
    "cpus",
    "diskpart",
    "distrobox",
    "edc",
    "efi",
    "elgato",
    "ghostty",
    "ghostty's",
    "gpt",
    "hsiao",
    "hyprctl",
    "kvm",
    "limine",
    "lossily",
    "lossy",
    "luks",
    "macbook",
    "ntfs",
    "nvme",
    "omakase",
    "omarchy",
    "podman",
    "ryzen",
    "sudoedit",
    "sunny's",
    "ultrawide",
    "unintuitive",
    "vfat",
    "wayblue",
    "yay",
    "yubikeys",
]
