words = [
    "agrippaindustries",
    "alation",
    "alnum",
    "asus",
    "bcdboot",
    "btrfs",
    "buildable",
    "caml",
    "catppuccin",
    "chezmoi",
    "cpus",
    "cuda",
    "dashmap",
    "diskpart",
    "distrobox",
    "edc",
    "efi",
    "elgato",
    "flexoki",
    "foveated",
    "fpga",
    "ghostty",
    "ghostty's",
    "gpt",
    "hsiao",
    "hyland",
    "hyprctl",
    "impactful",
    "imu",
    "jetson",
    "jira",
    "jtag",
    "krajancich",
    "kvm",
    "laude",
    "lcr",
    "limine",
    "lossily",
    "lossy",
    "lukehsiao",
    "luks",
    "macbook",
    "mcp",
    "memoriam",
    "microsystems",
    "mjpeg",
    "natively",
    "nginx",
    "ntfs",
    "nvme",
    "omakase",
    "omarchy",
    "outsized",
    "palantir",
    "palo",
    "podman",
    "pythonpath",
    "ryzen",
    "sudoedit",
    "sunny's",
    "tonari",
    "ultrawide",
    "unintuitive",
    "url's",
    "vannevar",
    "vannevar's",
    "vfat",
    "vivobarefoot",
    "vpc",
    "wayblue",
    "wetzstein",
    "winstein",
    "wirthlin",
    "worktree",
    "xilinx",
    "yay",
    "yubikeys",
    "zappos",
]
