words = [
    "alation",
    "asus",
    "bcdboot",
    "btrfs",
    "catppuccin",
    "chezmoi",
    "cpus",
    "diskpart",
    "distrobox",
    "edc",
    "efi",
    "elgato",
    "flexoki",
    "foveated",
    "fpga",
    "ghostty",
    "ghostty's",
    "gpt",
    "hsiao",
    "hyland",
    "hyprctl",
    "impactful",
    "jira",
    "jtag",
    "krajancich",
    "kvm",
    "laude",
    "lcr",
    "limine",
    "lossily",
    "lossy",
    "lukehsiao",
    "luks",
    "macbook",
    "memoriam",
    "ntfs",
    "nvme",
    "omakase",
    "omarchy",
    "podman",
    "ryzen",
    "sudoedit",
    "sunny's",
    "ultrawide",
    "unintuitive",
    "vfat",
    "vivobarefoot",
    "vpc",
    "wayblue",
    "wetzstein",
    "winstein",
    "wirthlin",
    "xilinx",
    "yay",
    "yubikeys",
]
