history_filter = [
  "^aws-mfa",
  "^b3sum",
  "^brew",
  "^cargo install",
  "^cargo install-update",
  "^cat",
  "^cd",
  "^chezmoi",
  "^choose",
  "^cp",
  "dnf upgrade",
  "^fg",
  "^git",
  "^hx",
  "^jj",
  "^just",
  "^la",
  "^ls",
  "^mkdir",
  "^mosh",
  "^mv",
  "^numbat",
  "^nvim",
  "^open",
  "^paru",
  "^pass",
  "^poetry",
  "^rg",
  "^rm",
  "^rustup self",
  "^rustup update",
  "^sudoedit",
  "^systemctl poweroff$",
  "^systemctl reboot$",
  "^tldr",
  "^tree",
  "^units",
  "^vim",
  "^yay",
  "^zathura",
  "^zellij",
]

enter_accept = true

[sync]
records = true
